# fly.toml app configuration file generated for hala-d01gzg on 2025-05-11T06:43:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hala-d01gzg'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
